### ISSUE TITLE
Repackage Roles from Prod

### ISSUE THREAD

**Issue by GaryRidgway** [ITS-UofIowa/its.uiowa.edu#114]
Admin views now requires the "Use the administration pages and help" permission for some roles to be able to filter or search the admin views interface. This is logged as a bug by other users in this issue here (https://www.drupal.org/project/admin_views/issues/3096612). This needs to be bundled in features.

**Comment by joewhitsitt** [comment]
Done https://github.com/ITS-UofIowa/its.uiowa.edu/commit/e82099ed167d4bd81433a7f293bc296b2ce803f7
