### ISSUE TITLE
Request FM for common building names

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#13]
We would like to request from FM to get this building names added as the common name.
- 108 River Street (RIV8) – Division of Performing Arts
- 111 Church Street – Obermann Center for Advanced Studies
- -2656 Crosspark Road (MTP2) – UI Research Park
- -2660 Crosspark Road (MTP1) – UI Research Park
- -2662 Crosspark Road (MTP4) – UI Research Park

**Comment by adamdelaney** [comment]
A request has been made via email to Facilities Management from Joe on Nov 21, 2016

**Comment by joewhitsitt** [comment]
@adriennecoon 
Facilities updated several buildings to instead use their common name which were automatically updated on the Maps and ITS website. Among those was the Obermann center and the crosspark road addresses (now Myriad Technology Plaza). 108 River is still waiting on a name.

It looks as though other plain street address buildings were added recently, so I am sure this will be a continuous cycle.
