### ISSUE TITLE
Add moderation workflow for alert content type creation

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#15]
- Third tier can create but not publish
- Can save/publish trigger an email to the HD so they know immediately when the alert has been posted and to publish it? 1. Workflow: Email to Helpdesk-notify@list.uiowa.edu
- Training/communication of this change will be important

**Comment by adamdelaney** [comment]
I think we should weigh the pro/con to adding moderation to the alerts content type. The alternative would be:
- node option permission: publish alert for HD/HD Student only
- unpublish pre_save check user role, if not HD/HD Student trigger email
moderation might work for the short term, but additional functionality we want to add (field_attach_update, etc.) may have struggles with the moderation logic.

**Comment by adamdelaney** [comment]
We want the non-workbench option, where third tier editors can create and save (not publish) an alert. On save by a third tier editor, an email should be sent to helpdesk-notify@list.uiowa.edu that a new alert is waiting to be published, it doesn’t need to print all the copy since they need to login to review anyways.

**Comment by adriennecoon** [comment]
This works really well and as expected. The only thing that would make it better is adding a publish button on the unpublished alert page from the email. Is this possible? Otherwise, editors have to search for it in the dashboard view, which is a little clunky.

**Comment by adamdelaney** [comment]
There are 2 issues with adding a publish button in the email:

1. We want them to review the actual content
2. There would be a technical issue, due to the fact that we need them to authenticate to the site in order to perform operations such as publishing content.

We could take them to the node edit page, but that would return a 403 if the user was not already logged into the site.

**Comment by adriennecoon** [comment]
Never mind my previous request--I was looking at the alert while masquerading as a third tier member and didn't see the editing functionality. This works as expected and approved.
