### ISSUE TITLE
Double View All Link on Recent News Block (e.g. /students)

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#19]
One is pointing to feed, the other to /news. Should probably get rid of the feed version...
![double-news-footer-link](https://cloud.githubusercontent.com/assets/1016880/20674807/d57890fc-b54f-11e6-8b4d-a4844415d753.png)

**Comment by adriennecoon** [comment]
Yes, please remove the additional link for the feed.

**Comment by adamdelaney** [comment]
This should be resolved now in dev. Let me know if you find other instances of this.
