### ISSUE TITLE
Available software view

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#25]
Requirements for available software search page
1.	Add editable content block to the top of page that will include an introductory paragraph about who the software is licensed for and that users will be asked to login with HawkID and password to verify access under licensing terms. Want full WYSIWYG. May want to add photos here as well. 
2.	Add editable sidebar to right side of page, similar to the audience pages or alerts and outages page. The same sidebar will be used on all software pages that are children to this main page. Example links might include:
a.	Link to computer purchasing page
b.	How to get software help or training (HD, Lynda, etc.)
c.	 Link to Virtual Desktop
d.	Link to software request form (campus software licensing)
3.	Create sortable view of all available titles beneath content block.
a.	Unset view will display all titles in a list, alphabetized by title 
b.	Titles can be sorted by: 
i.	Title search (text field where users can search by title—auto populate list like old support article view?)
ii.	Audience (students, staff/faculty) (dropdown list)
iii.	Category or Type of software (statistical, collaboration, etc.) (dropdown list)
iv.	Platform (Mac, Windows, Linux) (dropdown list)
4.	Software information to be displayed:
a.	Software title: Software title is a hyperlink that goes to applicable page—either the software download page or another page to get further information. (For example Microsoft Office would go to: How to install Office ProPlus and SPSS would go to SPSS page on software download site) Or "download now" button/link
b.	Software audience
c.	Software category
d.	Platform
e.	Software image (if available, default graphic if not)
f.	Maybe…short description of what the software does or how it can be used. Or will category be descriptive enough?
g.	More info/Details--licensing information

Requirements for making the current software template work for this sortable view:

1.	Add audience checkbox (students, fac/staff)
a.	Multiple ok?
2.	Add category checkbox
a.	Multiple ok?
b.	Adrienne/Tracey to come up with categories
c.	It would be nice if Adrienne/Tracey could also maintain this list if additional categories need to be entered
3.	Add platform checkbox
a.	Multiple ok
4.	Add URL field
a.	Hyperlink the software title to this page
5.	Add logo image upload (maybe, is it possible?)
a.	This is a nice to have and not mandatory

**Comment by adriennecoon** [comment]
Questions to be discussed: 
1.	Does it make sense to to force the current reviewed software content types into this view or start a new content type from scratch? 
a.	There are over 1,368 reviewed software titles in Drupal. We probably don’t want all of these to show up in the available software listing. 
b.	There are 42 software titles on the Software Download site (that I can see after logging in as a staff member).
c.	If we use the current software content type, can/should we add a simple checkbox to have that software item listed in the grid view?
d.	We will want to eventually ‘hide’ all of the reviewed software titles and only show titles that are available to download.
2.	Who is expected to maintain this content? (TRACY/TRACEY answer)
a.	If we want to display software logos, who would be expected to search for it and add it? Who will be expected to learn the software enough to be able to categorize it?
3.	Some links go to download installs and others go to support articles with information about how to install. How do we account for these differences?
a.	Add a hyperlink field where any link can be added. This will have to manually maintained. Any way around this?
4.	What about titles that don’t have installs or aren’t currently listed on the Software Download site? Ex. Qualtrics
5.	Do some of the types of software reviewed need to change? 
a.	For example, this one seems out of place: https://its.uiowa.edu/campus-software-program/microsoft-software-overview 
b.	For the searchable list, we would want individual titles to be listed, rather than hub-type pages.

**Comment by adriennecoon** [comment]
I got some clarifications regarding this view: 

1. Yes, this view will replace the departmental, fac/staff home use, and student software lists. 

1. I will be the one to maintain the publically viewed content and extra fields that we add (image/logo, platform, etc.). Tracey can probably just email me when a new software is ready for my touch, but a possibly workflow solution might be nice as long as it doesn't take a lot of development work.

**Comment by joewhitsitt** [comment]
A question that came up in our last discussion is where is the new view going to live and what other changes to the url path/way finding are going to change.

**Comment by joewhitsitt** [comment]
For now I have created a rough draft on the DEV site at /campus-software-program/software-list and disabled the student/department/staff&faculty displays and menu items.

I was confused about what was displayed in this view versus what we previously talked about/what was mentioned in this issue. Did you want the logo, short description, and more details in this view or just on the node page for each piece of software?

I left the how to obtain field as is for now. It is essentially a title/link field that is managed through a taxonomy because Tracey wanted to save her common values. I guess with linking directly to a software title's download, this makes this workflow a bit of a hassle, but I am not sure of a better way to get the both of best worlds. It gets more complicated because this is a multi value field.

Ideally, I wanted this table to be column sortable, but because everything besides the title is a multi field, there is no way to column sort. Filter is about all we can do.

As I was building this, I came up with a few additional questions:
- Is anything happening to the technology review process content? Is the menu in the current form still needed?
- Could the "editable sidebar" (issue summary item 2) be a manageable menu? (looks like links)
- What is the future of the Software Licensing and Acquisition info center?

**Comment by joewhitsitt** [comment]
After discussion:

- Look into basic page override with planted available software view and separate menu.
- Leave Software Licensing stuff alone except for removing old offered views and redirecting those links to the new basic page.
- View table should include short description field, logo, and direct link (new field). Look for ways to consolidate table (tooltips, modals, collapsible, styles)
- Remove links from categories, platforms and audiences.
- Leave obtain field/taxonomy alone, except for removing it from table view.

**Comment by joewhitsitt** [comment]
After today's discussion, development on the software content type has been halted. ITS is considering a separate content type to house both software and hardware that is separate from the existing software licensing content type.

**Comment by joewhitsitt** [comment]
View display needs to be disabled, and the previous offered view displays need to be reenabled

**Comment by joewhitsitt** [comment]
Disabled new view and reverted campus software program page code back to displaying old view.

**Comment by joewhitsitt** [comment]
Changing directions on this one. We will be utilizing the existing info center content type to create audience focused "software info centers." Development of that has been moved to issue #48
