### ISSUE TITLE
Better formatting of updates in alert email

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#27]
It's really hard to read the update section of an alert email when an alert has several updates. Maybe a bulleted list? Screenshot of what an alert with several updates looks like: 
![alert updates](https://cloud.githubusercontent.com/assets/24274784/21021543/91d114f4-bd3e-11e6-9101-a965e9ba17ba.JPG)

**Comment by joewhitsitt** [comment]
moved to blocked until we finalize #18

**Comment by joewhitsitt** [comment]
are updates to be included in the new format?

**Comment by joewhitsitt** [comment]
Same digest styles/formatting for manually triggered instant email.

**Comment by joewhitsitt** [comment]
@adriennecoon is this what you had in mind for the manual instant email?
![instant-updates](https://cloud.githubusercontent.com/assets/4663676/22128058/6d39f6be-de64-11e6-8027-0088e70a0762.png)

**Comment by joewhitsitt** [comment]
Tested on the mac and my windows virtual. Pushed to DEV if you want to test it.
