### ISSUE TITLE
Pages deleted over two months ago are still showing up in search

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#29]
Should we continue to wait or is something up? I don't recall it ever taking this long in the past. Any ideas? 

Many support articles from this search were deleted over two months ago and are showing as 404: https://its.uiowa.edu/google-search?search=project+management

**Comment by joewhitsitt** [comment]
Continue to wait. We have no control over Google's indexing process besides what we are already doing (sitemap, google analytics, 404s, etc.)
