### ISSUE TITLE
"Support Articles" header under "How to and support" tab on info centers looks odd

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#30]
Was that header always there? Or was it bigger before? It looks out of place now that I'm noticing it. Can we make the size larger or remove it entirely? 

https://its.uiowa.edu/duo#!how-to-and-support

**Comment by joewhitsitt** [comment]
Design wise, it looks odd, but yes, it is supposed to be there. That How-To and Support tab could contain more than just support articles. Getting help, Internal, Training, Lynda Links which I think are all labels styled the same size.

@adamdelaney do you have any input on this?

**Comment by adriennecoon** [comment]
Could we make it the same size as "Current Status" and "Maintenance" found under the IT Service Alerts? The sizing is really throwing me off and I don't like how it's smaller than the support article category immediately under it.

**Comment by joewhitsitt** [comment]
Actually, it was bigger before. When made the anchor links friendly, this changed the parent id that the style was targeting. Fixed the id.
