### ISSUE TITLE
Footer "Navigate" menu block not getting all the aria roles to be compliant.

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/its.uiowa.edu#34]
Doesn't seem to have the same structure as other menu blocks

- div - navigation
- ul - menubar
- li - presentation
- a - menuitem

Todd might send some additional examples.

**Comment by adamdelaney** [comment]
I've pushed a fix for this into dev, see commit: a21e026fc19bae8f8495c837d278ae594a5464ad
