### ISSUE TITLE
Add logo field to software content type

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#37]

**Comment by joewhitsitt** [comment]
holding off until i know for sure where this is displayed

**Comment by joewhitsitt** [comment]
This is going on table view and node.

**Comment by joewhitsitt** [comment]
After today's discussion, development on the software content type has been halted. ITS is considering a separate content type to house both software and hardware that is separate from the existing software licensing content type.

**Comment by joewhitsitt** [comment]
Changing directions on this one. We will be utilizing the existing info center content type to create audience focused "software info centers," where a logo field already exists. Development of that has been moved to issue #48
