### ISSUE TITLE
Restructure Software Node Display?

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/its.uiowa.edu#38]
What fields will be publicly visible? Are the other fields displayed to authenicated users similar to the alert content type, or is there some other display (admin software overview) that holds the internal information?

Are we keeping the software node sections (how to obtain, license restrictions, etc.), reorganizing the fields within them, moving to info center type display with tabs?

**Comment by adriennecoon** [comment]
Software content type fields to show on available software grid: 

- Software Title
- Short description
- Software description (display on 2nd page/tooltip/expandable section)
- How to obtain (new URL field, different from Tracey's how to obtain)
- Pricing (2nd page)
- Who can use it
- *Category (new)
- *Platform (new)
- *Logo (new)
- How can the software be used (maybe?)
- Where can the software be used (maybe?)
- ITS support (2nd page)
- ITS support articles (2nd page)
- Vendor support (2nd page, maybe?)
- Training (2nd page)

**Comment by joewhitsitt** [comment]
After today's discussion, development on the software content type has been halted. ITS is considering a separate content type to house both software and hardware that is separate from the existing software licensing content type.

**Comment by joewhitsitt** [comment]
Changing directions on this one. We will be utilizing the existing info center content type to create audience focused "software info centers." Development of that has been moved to issue #48
