### ISSUE TITLE
Alert workflow email - no email if saved by help desk roles.

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/its.uiowa.edu#39]
> Is it possible to have alerts that come from us [help desk staff] NOT send an email to helpdesk-notify for publishing?

on insert check user roles for help desk student and/or fulltime. if true, do not trigger email.

**Comment by joewhitsitt** [comment]
HD Student doesn't have alert creation capabilities and it doesn't look like many HD Students also get Third Tier, so I am only preventing emails from being triggered for HD Fulltime users. In DEV for review.

**Comment by adriennecoon** [comment]
Works perfectly! Yes, HD student won't have permissions to create an alert. This works exactly as expected. Thank you!
