### ISSUE TITLE
New software/hardware content type requirements

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#43]
Can we call it "Offered Software/Hardware"? 

Needed fields: 
•	Title—free text
•	Platform—selector/multi (use established taxonomy)
•	Category—selector (use established taxonomy)
•	Audience
•	How to obtain URL field (text + URL fields and maybe include a notes field/area to put in additional information?) I liked Joe's idea of having a "download" button too...
•	Description—free text. Information might include: description of the service, pricing information, links to resources, etc.)
•	Logo/image upload
•	Training/more help area to provide text links to info center, vendor site, support articles, licensing information, etc. Or maybe this could be combined with description field? 
•	Ability to designate as ‘home use only’. Or put this information in the description or how to obtain notes field? For example, faculty/staff can download Adobe Creative Cloud on personal computers for home use. For work machines, they should contact their local IT professional. Is there a good way to show this information/distinction? 
•	Distinction between Hardware or Software (drop down?) to show different views for these two categories

**Comment by joewhitsitt** [comment]
This issue has expanded into #48. Closing this task.
