### ISSUE TITLE
IT Service Alerts updates

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#57]
I got this request for updates to the IT Service alerts from Jamie Matthews:

- If buildings are selected, they should display in the daily digest. Display as list items under the body of the alert.
- Ability to copy over a previous alert to a new alert
- Figure out what to do with the long list of services since it will only continue to grow. We waste time searching for the right one since the names/titles are often not descriptive of the actual service  
- Third tier editors should have the ability to edit/delete alerts (unless it really screws up workflow)

**Comment by adamdelaney** [comment]
Closing in favor of #65, #70, #66
