### ISSUE TITLE
Reformat email for alert updates.

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#64]
_relates to 1b on requirements document_

Remove or re-style to bulleted list implementation.

**Comment by GaryRidgway** [comment]
@adriennecoon  I wanted to get clarification with you about some things before I went ahead and did work on this. When we remove the Bulleted list implementation, I was wondering which format you wanted us to change it to. I’ve put some example formats below for you to choose from with some example text. If you have any other ideas for a different format, please let me know. Also Note that the styling on these will not be the exact same for what it will be in the emails, as this is styled the way that github has it's default styles.

----------------------------------------------

```This implementation Would be a table with a structured framework. It would contain all of the updates and their date-times.```

**UPDATES**

Update Message | Date
------------ | -------------
This issue has been resolved. Please [contact the ITS Help Desk](https://github.com/ITS-UofIowa/its.uiowa.edu/issues/64) if you experience further issues accessing. |Jan 16 7:30am
Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. |Jan 17 1:45pm
Leverage agile frameworks to provide a robust synopsis for high level overviews. |Jan 18 5:00pm
Collaboratively administrate empowered markets via plug-and-play networks. |Jan 19 8:15am
Efficiently unleash cross-media information without cross-media value. |Jan 20 9:30am

----------------------------------------------

```This implementation would be just an un-indented version of the bulleted list. It would contain all of the updates and their date-times.```

**UPDATES**
This issue has been resolved. Please [contact the ITS Help Desk](https://github.com/ITS-UofIowa/its.uiowa.edu/issues/64) if you experience further issues accessing. Jan 16 7:30am
Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Jan 17 1:45pm
Leverage agile frameworks to provide a robust synopsis for high level overviews. Jan 18 5:00pm
Collaboratively administrate empowered markets via plug-and-play networks. Jan 19 8:15am
Efficiently unleash cross-media information without cross-media value. Jan 20 9:30am

----------------------------------------------

```This Implementation would show One update and a view more link. It would contain the most recent update with it's date-time, and then link off to the alerts page for the user to read all of the other alerts.```

**UPDATES**
This issue has been resolved. Please [contact the ITS Help Desk](https://github.com/ITS-UofIowa/its.uiowa.edu/issues/64) if you experience further issues accessing. Jan 16 7:30am
[View More Updates Here...](https://github.com/ITS-UofIowa/its.uiowa.edu/issues/64)

**Comment by adriennecoon** [comment]
@GaryRidgway How about version 2 with some modifications:  Append "**UPDATE**:" above each update and "**ORIGINAL NOTICE**:" above the original alert. Dates and times at the end. Most recent update at the top.

**Comment by joewhitsitt** [comment]
This has been reviewed and deployed.
