### ISSUE TITLE
Add building information to alert daily digest/alert instant emails.

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#65]
_relates to 1f on requirements document_

Display as list items under the body of the alert.

**Comment by GaryRidgway** [comment]
completed in commit https://github.com/ITS-UofIowa/its.uiowa.edu/commit/441a56f9284ad187cca6a564b86c5236bdf1967d

**Comment by adriennecoon** [comment]
Can I see something to review for this?

**Comment by joewhitsitt** [comment]
This has been reviewed and deployed.
