### ISSUE TITLE
Implement chosen on alert node edit form.

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#66]
_relates to 1d on requirements document_

- [x] Implement for info_center entity reference field.
- [x] Implement for building entity reference field.

**Comment by GaryRidgway** [comment]
added here https://github.com/ITS-UofIowa/its.uiowa.edu/commit/32cd50baeb581c419832a6198e2957b1bd30d4c9

**Comment by adriennecoon** [comment]
I don't know what any of this means.

**Comment by adamdelaney** [comment]
We have implemented a UI improvement that allows users to select building and info center references in a more intuitive way. To demo this functionality add a new Alert node. Open the Services or Building fieldset and add a reference. The new widget allows users to search and cleans up the long checkbox interface.

<img width="1053" alt="screen shot 2018-02-02 at 12 47 48 pm" src="https://user-images.githubusercontent.com/1016880/35749562-8e42590e-0817-11e8-9de7-55c0665cf4ca.png">
