### ISSUE TITLE
Investigate last updated timestamp logic for alerts

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#67]
_relates to 1e on requirements document_

When a third tier support group creates an alert and we publish it, the alert has a "last updated" timestamp on it that makes it look like there were updates to it when it’s new. I'd like to remove the "last updated" time stamp if the alert has never been published

**Comment by GaryRidgway** [comment]
in `modules->custom->its_content_types.module`

```
case 'alert_node_changed':
        if (count(node_revision_list($node)) > 1) {
          $markup = format_date($node->changed, 'long');
        }
        else {
          $markup = '';
        }
        // Render using field markup via d.o. psuedo_field.
        $node->content[$field_name] = array(
          '#pseudo_field' => TRUE,
          '#label_display' => 'inline',
          '#field_name' => $field_name,
          '#markup' => $markup,
        );
        break;
```

Controls this.

**Comment by adamdelaney** [comment]
Print all the time for all alerts

**Comment by GaryRidgway** [comment]
done in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/917c22ce409364a1f6098613e865226fd778e998
