### ISSUE TITLE
Implement custom publishing option to remove alerts tab

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#68]
_relates to 1j on requirements document_

I would suggest implementing custom_pub module and adding a new custom publishing option (i.e. Remove alerts display). In hook_node_preprocess we could check for that option and unset the alerts fieldgroup.

**Comment by GaryRidgway** [comment]
done in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/9d535e596b0e0721b55a8c4e927e10e47b5f883c

**Comment by GaryRidgway** [comment]
capitalized the Label in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/ea95d9ae36ed0938de170bf8f0148ef49317aeb5

**Comment by adriennecoon** [comment]
I don't know where to find this. Can someone show me?

**Comment by adamdelaney** [comment]
We have implemented a new publishing option to remove the "IT Service Alerts" tab on info center. To demo this functionality go to an info center node (https://its.dev.drupal.uiowa.edu/node/209). Click on "Publishing Options" in the left vertical tab sidebar. You'll see a new publishing option "Hide Alerts" under the moderation state dropdown. Toggle this checkbox to hide the alerts tab.

**Comment by adriennecoon** [comment]
I'm not seeing the ability to remove alerts off of info centers in prod. Did this one get missed?
