### ISSUE TITLE
Set persistent contextual link icon for alerts within panel collapsible.

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#69]
These panels show on the `/alerts` page.

**Comment by GaryRidgway** [comment]
completed in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/4a7a67aa14c4a06405afb118c8fc584586589729 and https://github.com/ITS-UofIowa/its.uiowa.edu/commit/224c2df9dd1a9d16d9e8e1a0f2217122d838e0b8

**Comment by GaryRidgway** [comment]
better scoping in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/c6edfee280123238461e44c8379d31b7c4460f0f

**Comment by adriennecoon** [comment]
Looks good.
