### ISSUE TITLE
Investigate copy alert node functionality.

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#70]
_relates to 1c, 1h on requirements document_

My initial thought is to implement an action button on the node edit form (i.e. `clone alert`). This button could create a new alert node object and copy over the relevant fields. The button would re-direct you to the new node.

**Comment by GaryRidgway** [comment]
added in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/dd1f436b730636a20c1e5a85bbfa1da9244bde88 and https://github.com/ITS-UofIowa/its.uiowa.edu/commit/fd6dc553ed6c4b8e7829425c9c69c8c64ed47332

**Comment by adriennecoon** [comment]
Where can I find this? Again, I don't know what I'm reviewing.

**Comment by adamdelaney** [comment]
Go to an existing alert node (https://its.dev.drupal.uiowa.edu/alert/111146). In the local menu tasks there is a "Clone this alert" link.

<img width="817" alt="screen shot 2018-02-02 at 12 54 55 pm" src="https://user-images.githubusercontent.com/1016880/35749788-5cedcf5e-0818-11e8-9149-e46bd2f501ec.png">
