### ISSUE TITLE
Implement an ICS download button for alerts.

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#71]
Honors and OneIT Intranet both have ics integration using date_ical and hook_extra_fields().

**Comment by GaryRidgway** [comment]
added here https://github.com/ITS-UofIowa/its.uiowa.edu/commit/86a5547f13848c803e3c07aa6add7502bad0860e

**Comment by adriennecoon** [comment]
Don't kill me. Jamie doesn't want this anymore. Please remove the iCal functionality. She only wants it for planned maintenance because it doesn't make sense to have it for outages. I think it should be all or nothing. If you disagree, let me know.

**Comment by GaryRidgway** [comment]
This is now removed with https://github.com/ITS-UofIowa/its.uiowa.edu/issues/71
