### ISSUE TITLE
Add layout manager and bt_button to wysiwyg

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#73]
_relates to 3 on requirements document_

**Comment by GaryRidgway** [comment]
added in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/f8055b7c7a2e0aea09dbf25fe227812743043259

needs to be tested in dev environment

**Comment by adriennecoon** [comment]
I don't understand what to review here.

**Comment by adamdelaney** [comment]
We have implemented 2 new buttons into the WYSIWYG. The layout manager allows editors you select from a few layout templates and place content into columns.
<img width="963" alt="screen shot 2018-02-02 at 12 58 32 pm" src="https://user-images.githubusercontent.com/1016880/35750010-2298800a-0819-11e8-8fa6-6bd1982c2820.png">
<img width="1075" alt="screen shot 2018-02-02 at 12 59 48 pm" src="https://user-images.githubusercontent.com/1016880/35750012-24e8eb74-0819-11e8-9e81-0b85872237f6.png">

Btbutton allows editors to insert a link styled as a button.
<img width="881" alt="screen shot 2018-02-02 at 12 59 57 pm" src="https://user-images.githubusercontent.com/1016880/35750027-35744560-0819-11e8-8cb1-380504097afb.png">
<img width="466" alt="screen shot 2018-02-02 at 1 00 05 pm" src="https://user-images.githubusercontent.com/1016880/35750030-370b2b64-0819-11e8-96bf-b3c0b6b5c2bc.png">

To demo, go to any node that has a WYSIWYG and insert content into the new widgets.
