### ISSUE TITLE
Update field label for Lynda training

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#74]
_relates to 6 on requirements document_

Change the Lynda header under the How to and Support tab of info centers from “Lynda.com Links” to “Lynda Video Tutorials.”

**Comment by GaryRidgway** [comment]
done here https://github.com/ITS-UofIowa/its.uiowa.edu/commit/61c87281e6401c1f50ad194f1a368958ab4d0fa6

**Comment by adriennecoon** [comment]
Looks good on Dev. Ok to push to prod.
