### ISSUE TITLE
Implement accordions and textarea paragraphs bundles to support articles

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#75]
_relates to 7b on requirements document_

Investigate programmatically moving the body and faq data into paragraph entities.

**Comment by joewhitsitt** [comment]
Show the snp_textarea and snp_accordion bundles on support articles in DEV side by side with support article body/faq so it can be compared.

Also look into add to top of list solution.

**Comment by adamdelaney** [comment]
<img width="672" alt="screen shot 2018-01-26 at 2 07 35 pm" src="https://user-images.githubusercontent.com/1016880/35458627-b41cef9c-02a2-11e8-9113-a698adf200c6.png">

I've created the paragraphs demo on the dev site. See: https://its.dev.drupal.uiowa.edu/node/111131

**Comment by adriennecoon** [comment]
@adamdelaney Is it possible to have both? Keeping the current FAQ functionality and using this new paragraphs demo IF people want to use it?

**Comment by joewhitsitt** [comment]
As discussed at the Friday meeting, keep existing body/faq fields on support articles and remove paragraph demo

**Comment by adamdelaney** [comment]
This was only implemented as a demo in dev so there is nothing we need to do for this.
