### ISSUE TITLE
Investigate possibly removing general field group from alert and basic page

### ISSUE THREAD

**Issue by GaryRidgway** [ITS-UofIowa/its.uiowa.edu#78]
The general section is empty and therefore not necessary, if there is anything that is supposed to go in here, we may need to double check to make sure.

**Comment by joewhitsitt** [comment]
Looks like the general field group is a remanent of a decision to "standardize" field_groups on content types we touched to use "Standard" instead. The general groups (alert, basic page) weren't completely removed from the feature.

**Comment by adriennecoon** [comment]
I don't know what any of this means or what I should review.

**Comment by adamdelaney** [comment]
There is nothing to review this is an internal clean up job.
