### ISSUE TITLE
Edit titles

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#79]
https://its.uiowa.edu/campus-software-program/software-list
Edit titles to UI Offered Software and Technology Tools (in two spots)
 
https://its.uiowa.edu/campus-software-program/software-list/department
Edit titles to UI Department Software and Technology Tools (in two spots)
 
https://its.uiowa.edu/campus-software-program/software-list/fs
Edit title to Faculty & Staff Software and Technology Tools
Edit title to Faculty & Staff Home Use Software and Technology Tools
 
https://its.uiowa.edu/campus-software-program/software-list/student
Edit title to Student Software and Technology Tools

**Comment by joewhitsitt** [comment]
This is the menu: https://its.uiowa.edu/admin/structure/menu/manage/menu-campus-software-program (this is a change in PROD)

These are the pages and are packaged up in ITS Pages: https://its.uiowa.edu/admin/structure/pages/edit/page-technology_reviews
https://its.uiowa.edu/admin/structure/pages/edit/page-ui_offered_software (has variants)

**Comment by GaryRidgway** [comment]
added in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/01c2c3b2cb90e1661409e4468744b04f8960ff7e

Changed the Panel UI Offered Software -> Variants -> Software List -> Content Title to “UI Offered Software and Technology Tools”

_______________________________________________________________________________________________________

Changed the Panel UI Offered Software -> Variants -> Department -> Content Title to “UI Department Software and Technology Tools”

Changed the View Campus Software Program -> Department Software -> Title to “UI Department Software and Technology Tools”

_______________________________________________________________________________________________________

Changed the Panel UI Offered Software -> Variants -> Faculty & Staff Software -> Content Title to “Faculty & Staff Software and Technology Tools”

Changed the View Campus Software Program -> Faculty & Staff -> Title to “Faculty & Staff Home Use Software and Technology Tools”

_______________________________________________________________________________________________________
Changed the Panel UI Offered Software -> Variants -> Student-> Content Title to “Student Software and Technology Tools”

**Comment by adriennecoon** [comment]
Looks good on dev. Ready to promote.
