### ISSUE TITLE
add unique aria-labels to menu_block blocks

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/its.uiowa.edu#82]
similar to: https://github.com/ITS-UofIowa/law.uiowa.edu/blob/master/themes/law_radix/includes/block.inc#L48

**Comment by GaryRidgway** [comment]
added in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/918875dd32ca6466b852b74b9cc0d27a4765183f

**Comment by adriennecoon** [comment]
I don't know what I'm supposed to review here.

**Comment by adamdelaney** [comment]
There is nothing to review here.
