### ISSUE TITLE
Resolve error with sitenow_paragraphs and features field issue

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#92]
This error occurs when I sync the production site locally.
```
WD features: Attempt to create field field_snp_content_blocks  [error]
failed: Attempt to create field name field_snp_content_blocks
which already exists, although it is inactive.
```

**Comment by joewhitsitt** [comment]
I think this can be resolved by running the following off-hours in PROD. Off-hours because `cache_form` can affect users if currently interacting with a form.

```
drush sqlq "TRUNCATE TABLE cache;"
drush sqlq "TRUNCATE TABLE cache_form;"
drush sqlq "TRUNCATE TABLE cache_features;"
```

**Comment by joewhitsitt** [comment]
I believe the above fixed it. Synced down without seeing this issue. Needs tests.

**Comment by joewhitsitt** [comment]
@GaryRidgway said he doesn't see this anymore. Closing for now.
