### ISSUE TITLE
Resolve overflow-x issue

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#96]
## Overview
A horizontal scroll bar is implemented on the homepage and potentially other pages because of an overflow issue. I believe the overflow is due to the row class on the `#content` div.  The row class utilizes negative margin pushing the content outside of the normal 100% block level element and then a corresponding col class is implemented with padding.
<img width="318" alt="screen shot 2018-04-26 at 12 50 45 pm" src="https://user-images.githubusercontent.com/1016880/39322812-9a0d166e-4950-11e8-8a72-26e34ce3953e.png">

## Possible solutions
We can add an `overflow-x: hidden` to a parent container. For example:
```
.main { overflow-x: hidden; }
```

**Comment by GaryRidgway** [comment]
Fixed this in most recent update
